# Generated by Django 2.2.5 on 2019-09-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
