# Generated by Django 2.2.5 on 2019-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
