# Generated by Django 2.2.5 on 2019-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followername',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
