# Generated by Django 2.2.5 on 2019-09-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
