# Generated by Django 2.2.5 on 2019-09-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190916_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
