# Generated by Django 2.2.4 on 2019-09-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
