# Generated by Django 2.2.5 on 2019-09-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_twitteruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='twitter_handle',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
