# Generated by Django 2.2.5 on 2019-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20190905_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='twitter_handle',
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='username',
            field=models.CharField(default='@NOT_PROVIDED', max_length=100, unique=True),
        ),
    ]
